### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#1]
Hi Pratima,

We'd be grateful if you could work on these tasks: 

- [ ] Top header
- [ ] Update email to contact@codefornepal.orgremove phone number
- [ ] hyperlink social media channels. Remove G+ Menu
- [ ] Remove: Events, Causes, Search and Update "NEWS" to blogs, and Donate now to Help us

Generally, I'd say, pls look at www.codefornepal.org and try to remove things/pages/content from the http://3.222.156.45/

More to come soon

**Comment by davidsth** [comment]
let's close this. I've broken down these changes in other issues.
