### ISSUE TITLE
Add projects from previous site

### ISSUE THREAD

**Issue by davidsth** [CodeforNepal/codefornepal.github.io#12]
Let's add ongoing projects for the time being in the homepage:

![image](https://user-images.githubusercontent.com/1936038/88483764-11161700-cf38-11ea-9f74-18fa0e08ab96.png)

Follow the template under _portfolio/project1.md

**Comment by davidsth** [comment]
@ravinepal  Let's add projects under the portfolio section instead. 

The Services we added can be about our mission and values.

**Comment by ravinepal** [comment]
Sorry, David. I missed this earlier. After thinking more, our homepage should have these sections 

- Our work (This should have our products and projects. We can highlight a few on the homepage and it can have its own page too.)
- Stories (We can highlight 2-3 most recent blogs on the homepage and link to the blog section.)
- About us (We can use the template on the homepage to share a bit about our history and timeline, and link to a page where we have more info on our mission and values.)
- Our team (Same as above. We use the template to feature a few members on the homepage and link to the team page for the rest of the core team members.)
- Contact Us 
- Footer
     - Code of Conduct
      - Privacy Policy
      - Copyright info
      - Links to Social media 

I also believe we should create a "Get Involved" page with ideas you have suggested. 

Looking forward to your feedback 

Here's the Google doc to plan our [content](https://docs.google.com/document/d/1-BbUzLr38HochuqMaPb0lFTrbCYpNDwuE4kW16sqBuc/edit#)
