### ISSUE TITLE
Upgrade netlify's OS from Ubuntu 16.04 to newer compatible OS

### ISSUE THREAD

**Issue by ayushsubedi** [CodeforNepal/codefornepal.github.io#139]
<img width="915" alt="image (1)" src="https://user-images.githubusercontent.com/45836811/203456117-50500371-28a6-4dc4-bb94-2a5ae33b8c45.png">

**Comment by davidsth** [comment]
Done. @ayushsubedi please share your email so I can add you to the netlify team.
