### ISSUE TITLE
Let's add code of conduct!

### ISSUE THREAD

**Issue by davidsth** [CodeforNepal/codefornepal.github.io#14]
A lot of open source projects and org https://www.contributor-covenant.org/

I don't think we need to include everything there but I think pledge and standards make sense.

There is a markdown version they've published (we could translate it to nepali as well!)

https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

I'd say we can add it to the legal page and rename it to Code of Conduct

**Comment by ravinepal** [comment]
Thanks, David. For now, let's use all of the text from here: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md (We can edit and translate later. I'll create an issue to set up a page and take it from there.)
