### ISSUE TITLE
Add C4N logo 

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#18]
Add this logo: 

Two options: 

- http://www.codefornepal.org/wp-content/uploads/2015/01/c4n_logo.png

- ![image](https://user-images.githubusercontent.com/3759081/88490109-1fc7f280-cf67-11ea-9351-f378f67d2f31.png)

This needs to be replaced: 
![image](https://user-images.githubusercontent.com/3759081/88490052-ab8d4f00-cf66-11ea-8390-015d46a6fbf5.png)

For more context:

We can add logo in the `_config.yml` file

Example here:
https://github.com/raviriley/agency-jekyll-theme/blob/master/_config.yml#L23

**Comment by davidsth** [comment]
do we have an svg version?

**Comment by ravinepal** [comment]
yup we do @davidsth: https://drive.google.com/drive/folders/13YLT7ahBg2_ephKKssvdizP7NcdAbAQF?usp=sharing
