### ISSUE TITLE
Navbar items overflow when window is under 992px

### ISSUE THREAD

**Issue by 1aurence** [CodeforNepal/codefornepal.github.io#23]
![navbar-ussie](https://user-images.githubusercontent.com/33357470/88864472-4ab67e80-d1d3-11ea-8bfc-e1f988df934a.png)

**Comment by davidsth** [comment]
I'm not seeing this issue on chrome. What browser did you use? Feel free to work on it and send a PR
![image](https://user-images.githubusercontent.com/1936038/88866181-e3e79400-d1d7-11ea-936c-a80a5eba90f9.png)

**Comment by 1aurence** [comment]
I was using Chrome, but after pulling the updates I no longer experience that happening.
