### ISSUE TITLE
Create Code of Conduct page 

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#28]
let's use all of the text from here: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md (We can edit and translate in Nepali later.) 

We will have the link to this page in the footer. We'd be grateful for your help @pratimakandel

**Comment by davidsth** [comment]
I think we've added code of conduct  here b0a1925 but We still need to link it as a page in our site. I'd probably replace this page with code of conduct for now https://code4nepal.github.io/website20/legal
