### ISSUE TITLE
Add Donate Button 

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#39]
Should we put this on the main nav bar and in the footer? 

Currently, we use PayPal to accept donations and have to manually send out tax receipts to donors. I'm curious if you know of automated systems?

**Comment by pratimakandel** [comment]
Not sure how to implement an automated receipts system..for now I can create a basic donate button in the nav bar and the footer. Let me know if this will work? @ishandongol @davidsth @1aurence 

![test](https://user-images.githubusercontent.com/39708188/90964775-86bac780-e491-11ea-94d5-86ced72f986e.png)

Footer: 
![test2](https://user-images.githubusercontent.com/39708188/90964781-95a17a00-e491-11ea-8c84-a10a1640307e.png)

**Comment by ishandongol** [comment]
Yeah works for me. But it will be better if we put just the donate button on **navbar**.

**Comment by ravinepal** [comment]
donate button in the nav bar and the footer sounds good, @pratimakandel

**Comment by pratimakandel** [comment]
#57 should fix this.
