### ISSUE TITLE
Fix the image render issues in blogs.

### ISSUE THREAD

**Issue by ishandongol** [CodeforNepal/codefornepal.github.io#52]
# Issue:

![Screen Shot 2020-08-22 at 17 15 49](https://user-images.githubusercontent.com/12002691/90955212-5aa44400-e49b-11ea-92eb-6a2114502506.png)

**Comment by pratimakandel** [comment]
PR #80 Fixed for the image render issue mentioned above. 
However, most images in the old posts are linked to the old website **https://codefornepal.org/wp-content/uploads/2020/02/nepalmap-552x1024.png**. Need to add correct links/pictures.
