### ISSUE TITLE
Update stories section with blogs we want to highlight

### ISSUE THREAD

**Issue by davidsth** [CodeforNepal/codefornepal.github.io#60]
@ravinepal  Could you please identify 3 blog posts we have that we can highlight in the stories section?

**Comment by ravinepal** [comment]
My 1st suggestion would be to consider creating a mechanism so the most recent two blogs.stories are highlighted automatically. This would prevent us from updating the site manually. 

If you strongly prefer, we manually highlight the stories, then here are the links: 

- https://codefornepal.github.io/website20/2020/02/nepalmap-federal-explore-and-understand-nepal-using-data/
-  https://codefornepal.github.io/website20/2020/05/google-data-now-shows-fewer-people-in-nepal-are-staying-indoors-amid-the-coronavirus-pandemic/
- https://codefornepal.github.io/website20/2019/09/my-journey-at-insight-workshop-through-the-hawkins-fellowship/

**Comment by davidsth** [comment]
Manual is a good first start and easily achievable. Small strides

**Comment by ravinepal** [comment]
i like the approach. see 3 blog suggestions above :)

**Comment by davidsth** [comment]
I think we also need to update the the css styles so this works properly. An example of how it should look:
![image](https://user-images.githubusercontent.com/1936038/93689466-bd89fa80-fa9c-11ea-8637-631fb6bd74a8.png)

**Comment by pratimakandel** [comment]
@ravinepal @ishandongol @davidsth Does this work? 

![save](https://user-images.githubusercontent.com/39708188/103484389-78c07000-4dbc-11eb-849e-6e707d048529.png)

**Comment by ishandongol** [comment]
Yeah but we need to make blog image compulsory or render placeholder for blogs with no images.

**Comment by pratimakandel** [comment]
@ishandongol 
yeah we should make it compulsory! also in case if there are no images, this is how it will look. Let me know if this works? 
![save](https://user-images.githubusercontent.com/39708188/103486137-83353680-4dc9-11eb-9f76-23188a672fdc.png)

**Comment by ishandongol** [comment]
Yup that works too.

**Comment by pratimakandel** [comment]
Pull Request #80
