### ISSUE TITLE
Add social media card 

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#61]
- [ ] Add social media card - description and logo so the display is more user friendly

How it looks currently 
![image](https://user-images.githubusercontent.com/3759081/93669527-dc6b9b00-fa62-11ea-9ce3-0ae49e2f13ce.png)

how it should look
![image](https://user-images.githubusercontent.com/3759081/93669555-0329d180-fa63-11ea-81b4-ef1b7dcb2812.png)

@davidsth @ishandongol @1aurence -- pls feel free to resolve this today if possible.

**Comment by ishandongol** [comment]
working on it

**Comment by ishandongol** [comment]
copied meta from our old website.
https://github.com/CodeforNepal/website20/pull/69

**Comment by ishandongol** [comment]
![Screen Shot 2020-09-19 at 23 52 13](https://user-images.githubusercontent.com/12002691/93686050-63f0f280-fad3-11ea-95b3-a171a8e9817d.png)
