### ISSUE TITLE
Create "Join us" page

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#62]
please create a "Join us" page. No need to put it on the main navbar. 

Here's the placeholder content to use:

You can help us and many in Nepal just from your couch or sofa. You can a designer, marketer, coder, writer, problem-solver, or anyone else and are interested in helping people make better use of technology, be digitally and data literate, then join us via: 
[Slack](https://join.slack.com/t/codefornepal/shared_invite/zt-fm07r7gz-97iagKnDNJ3DbX8QKR6Bxg) (Say hello and introduce yourself)
[Github](https://github.com/CodeforNepal) (You can start looking at projects and contribute by resolving issues or suggesting enhancements)
[Facebook ](http://facebook.com/codefornepal)
[Twitter ](https://twitter.com/codefornepal)
We also encourage you to explore our website, learn about our projects, and read the “[Code of Conduct](https://codefornepal.github.io/website20/codeofconduct/)” policy. 

If you are an Amazon shopper, you can help us by shopping through [smile.amazon.com](https://smile.amazon.com/ref=smi_ext_ch_47-3620037_dl?_encoding=UTF8&ein=47-3620037&ref_=smi_chpf_redirect&ref_=smi_ext_ch_47-3620037_cl) and selecting to support Code for Nepal.

**Comment by ishandongol** [comment]
sure working on it

**Comment by ishandongol** [comment]
https://github.com/CodeforNepal/website20/pull/64#issue-489765811

**Comment by ravinepal** [comment]
@ishandongol  - could you pls hyperlink "join us" page to"get involved" button on the homepage?

**Comment by ishandongol** [comment]
sure @ravinepal

**Comment by ravinepal** [comment]
https://codefornepal.github.io/website20/joinus/

**Comment by ravinepal** [comment]
@ishandongol - just flagging that the link for join us "get involved" does not work anymore. when you have time pls take a look, it is not urgent.

**Comment by ishandongol** [comment]
sure

**Comment by ishandongol** [comment]
@ravinepal is this resolved?
