### ISSUE TITLE
Create "Projects" page

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/codefornepal.github.io#63]
Placeholder content to come sooon..

**Comment by ravinepal** [comment]
content: 

Since 2014, our small community of volunteers, have organized digital workshops, conferences, provided scholarships, and built a series of products such as: 

[NepalMap ](https://nepalmap.org/)
[Sangraha](http://sangraha.org/) 
[AskNepal](https://asknepal.info/)


@ishandongol - pls use this for content for now.

**Comment by ravinepal** [comment]
@ishandongol - thank you for updating this section. Looks great! Can we still create a separate page for "Projects" when you have time, like you did with the "join us" page? 

I'd like to include rest of our projects, like we have done in our current site: https://codefornepal.org/projects/

**Comment by ishandongol** [comment]
separate page is also created.
