### ISSUE TITLE
Make fonts uniform across website. 

### ISSUE THREAD

**Issue by ishandongol** [CodeforNepal/codefornepal.github.io#65]
Make fonts identical to blog.

**Comment by ravinepal** [comment]
You can use Calibri (Body) fontsize 12 for paragraphs. 

Links should be blue:  #00ADEF

**Comment by ishandongol** [comment]
also gonna include bootstrap via scss.

**Comment by davidsth** [comment]
@ishandongol  can we close this?

**Comment by ishandongol** [comment]
will do
